spring.application.name=notification-service

# Server port (different de Auth qui est sur 8080)
server.port=8081

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# SMTP vers MailHog (pas de TLS, pas d'auth)
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

# URL de base du service Auth pour construire le lien de verification
app.auth.base-url=http://localhost:8080
